### ISSUE TITLE
[Bug]: Unsupported Model File

### ISSUE THREAD

**Issue by lannodev** [nomadkaraoke/python-audio-separator#197]
### Describe the bug

I am trying to use the UVR_MDXNET_KARA.onnx model but I am getting this error:

```log
INFO:audio_separator.separator.separator:Loading model UVR_MDXNET_KARA.onnx...
ERROR:audio_separator.separator.separator:IOError seeking -10MB or reading model file for hash calculation: [Errno 22] Invalid argument
ERROR : Unsupported Model File: parameters for MD5 hash 3795deb1231cee6d8b3483b608db90dd could not be found in UVR model data file for MDX or VR arch.
```
What could it be?

### Have you searched for existing issues?  🔎

- [x] I have searched and found no existing issues.

### Logs

```shell
WARNING:root:Coremltools is not installed. If you plan to use a CoreML Saved Model, reinstall basic-pitch with `pip install 'basic-pitch[coreml]'`
WARNING:root:tflite-runtime is not installed. If you plan to use a TFLite Model, reinstall basic-pitch with `pip install 'basic-pitch tflite-runtime'` or `pip install 'basic-pitch[tf]'
WARNING:tensorflow:From C:\Users\Luciano\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

C:\Users\Luciano\AppData\Local\Programs\Python\Python311\Lib\site-packages\pretty_midi\instrument.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\Users\Luciano\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('pyannote')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
► Starting 1/1:  Clayton & Romário - Morena
INFO:audio_separator.separator.separator:Separator version 0.18.3 instantiating with output_dir: C:\Users\Luciano\Music\Deezer Download\Cantae, output_format: mp3
INFO:audio_separator.separator.separator:Operating System: Windows 10.0.26100
INFO:audio_separator.separator.separator:System: Windows Node: LANNOPC Release: 10 Machine: AMD64 Proc: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
INFO:audio_separator.separator.separator:Python Version: 3.11.6
INFO:audio_separator.separator.separator:PyTorch Version: 2.4.0+cu124
INFO:audio_separator.separator.separator:FFmpeg installed: ffmpeg version 7.0.2-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
INFO:audio_separator.separator.separator:ONNX Runtime GPU package installed with version: 1.18.1
INFO:audio_separator.separator.separator:ONNX Runtime CPU package installed with version: 1.18.1
INFO:audio_separator.separator.separator:CUDA is available in Torch, setting Torch device to CUDA
WARNING:audio_separator.separator.separator:CUDAExecutionProvider not available in ONNXruntime, so acceleration will NOT be enabled
INFO:audio_separator.separator.separator:Loading model UVR_MDXNET_KARA.onnx...
ERROR:audio_separator.separator.separator:IOError seeking -10MB or reading model file for hash calculation: [Errno 22] Invalid argument
ERROR : Unsupported Model File: parameters for MD5 hash 3795deb1231cee6d8b3483b608db90dd could not be found in UVR model data file for MDX or VR arch.
```

### System Info

```shell
Operating System: Windows 11 Pro 24H2
Python version: 3.11.6
```

**Comment by lannodev** [comment]
Hi @beveradb 👋
I tried to install it using `pip install git+https://github.com/nomadkaraoke/python-audio-separator.git@maybe-fix-model-hash-seek-windows` but I received this error message:

```python
 pip install git+https://github.com/nomadkaraoke/python-audio-separator.git@maybe-fix-model-hash-seek-windows
Collecting git+https://github.com/nomadkaraoke/python-audio-separator.git@maybe-fix-model-hash-seek-windows
  Cloning https://github.com/nomadkaraoke/python-audio-separator.git (to revision maybe-fix-model-hash-seek-windows) to c:\users\luciano\appdata\local\temp\pip-req-build-mukoj3ww
  Running command git clone -q https://github.com/nomadkaraoke/python-audio-separator.git 'C:\Users\Luciano\AppData\Local\Temp\pip-req-build-mukoj3ww'
  Running command git checkout -b maybe-fix-model-hash-seek-windows --track origin/maybe-fix-model-hash-seek-windows
  Branch 'maybe-fix-model-hash-seek-windows' set up to track remote branch 'maybe-fix-model-hash-seek-windows' from 'origin'.
  Switched to a new branch 'maybe-fix-model-hash-seek-windows'
  Resolved https://github.com/nomadkaraoke/python-audio-separator.git to commit f9200916a5644d4e05a6b5d141ac11644912ccd2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy<2,>=1.23 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (1.23.5)
Requirement already satisfied: pyyaml in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (6.0)
Requirement already satisfied: ml_collections in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (0.1.1)
Requirement already satisfied: requests>=2 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (2.31.0)
Requirement already satisfied: rotary-embedding-torch<0.7.0,>=0.6.1 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (0.6.5)
Requirement already satisfied: six>=1.16 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (1.16.0)
Requirement already satisfied: beartype<0.19.0,>=0.18.5 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (0.18.5)
Requirement already satisfied: onnx2torch>=1.5 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (1.5.15)
Requirement already satisfied: librosa>=0.10 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (0.11.0)
Requirement already satisfied: scipy<2.0.0,>=1.13.0 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (1.13.1)
Collecting torch>=2.3
  Downloading torch-2.6.0-cp39-cp39-win_amd64.whl (204.1 MB)
     |████████████████████████████████| 204.1 MB 300 kB/s
Requirement already satisfied: samplerate==0.1.0 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (0.1.0)
Requirement already satisfied: tqdm in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (4.66.1)
Requirement already satisfied: julius>=0.2 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (0.2.7)
Requirement already satisfied: onnx>=1.14 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (1.15.0)
Requirement already satisfied: resampy>=0.4 in c:\users\luciano\appdata\local\programs\python\python39\lib\site-packages (from audio-separator==0.30.2) (0.4.2)
Collecting diffq-fixed>=0.2
  Using cached diffq_fixed-0.2.4.tar.gz (189 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Luciano\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\Luciano\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\Luciano\AppData\Local\Temp\tmpwn1j95x2'
       cwd: C:\Users\Luciano\AppData\Local\Temp\pip-install-kk6z1mle\diffq-fixed_20ca19091ca8497fb0f0ddcbf268f525
  Complete output (23 lines):
  Traceback (most recent call last):
    File "C:\Users\Luciano\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\Luciano\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\Luciano\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Luciano\AppData\Local\Temp\pip-build-env-_1hoj3nh\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "C:\Users\Luciano\AppData\Local\Temp\pip-build-env-_1hoj3nh\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
      self.run_setup()
    File "C:\Users\Luciano\AppData\Local\Temp\pip-build-env-_1hoj3nh\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\Luciano\AppData\Local\Temp\pip-build-env-_1hoj3nh\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
      exec(code, locals())
    File "<string>", line 48, in <module>
    File "C:\Users\Luciano\AppData\Local\Temp\pip-build-env-_1hoj3nh\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1010, in cythonize
      module_list, module_metadata = create_extension_list(
    File "C:\Users\Luciano\AppData\Local\Temp\pip-build-env-_1hoj3nh\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 845, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "C:\Users\Luciano\AppData\Local\Temp\pip-build-env-_1hoj3nh\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 117, in nonempty
      raise ValueError(error_msg)
  ValueError: 'bitpack.pyx' doesn't match any files
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/be/96/8ca5acf5ecfd4108aa6f345cef171f2fda0c081cf0e7430671712586f172/diffq_fixed-0.2.4.tar.gz#sha256=cbc906b76fa23d1cf3c0ae517fbab744d9624980a068fe7fbb00dede1d83208d (from https://pypi.org/simple/diffq-fixed/) (requires-python:>=3.7.0). Command errored out with exit status 1: 'C:\Users\Luciano\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\Luciano\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\Luciano\AppData\Local\Temp\tmpwn1j95x2' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement diffq-fixed>=0.2; sys_platform == "win32" (from audio-separator) (from versions: 0.2.4)
ERROR: No matching distribution found for diffq-fixed>=0.2; sys_platform == "win32"
WARNING: You are using pip version 21.2.4; however, version 25.0.1 is available.
You should consider upgrading via the 'C:\Users\Luciano\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
```

**Comment by beveradb** [comment]
https://github.com/nomadkaraoke/python-audio-separator/tree/main?tab=readme-ov-file#requirements-

> Requirements 📋
> Python >= 3.10

> Make sure you have Python 3.10 or newer installed on your machine.

**Comment by beveradb** [comment]
Also FYI I've merged my PR and released version `0.30.2` - so, try installing a newer version of Python (minimum 3.10) and the latest version of `audio-separator` 🙏

**Comment by lannodev** [comment]
Hi beveradb,
I did exactly as you asked and I'm still getting the same error :(

```log
cantae-tools on  master 
❯ pip show audio-separator
Name: audio-separator
Version: 0.30.2
Summary: Easy to use audio stem separation, using various models from UVR trained primarily by @Anjok07
Home-page: https://github.com/karaokenerds/python-audio-separator
Author: Andrew Beveridge
Author-email: andrew@beveridge.uk
License: MIT
Location: c:\users\luciano\appdata\local\programs\python\python310\lib\site-packages
Requires: beartype, diffq-fixed, einops, julius, librosa, ml_collections, numpy, onnx, onnx2torch, pydub, pyyaml, requests, resampy, rotary-embedding-torch, samplerate, scipy, six, torch, tqdm
Required-by: 
cantae-tools on  master 
❯ py --version
Python 3.10.0
cantae-tools on  master 
```

**Comment by lannodev** [comment]
If I try to use the model: `UVR_MDXNET_KARA_2.onnx,` the hash value is `1d64a6d2c30f709b8c9b4ce1366d96ee` and I can find it in the list:
https://raw.githubusercontent.com/TRvlvr/application_data/main/mdx_model_data/model_data_new.json

However, for the model `UVR_MDXNET_KARA.onnx`, the hash is `3795deb1231cee6d8b3483b608db90dd` and it does not exist in the list.

Another important point I noticed is that this is happening with models smaller than `10MB`.

![Image](https://github.com/user-attachments/assets/8eb3a525-5c82-49e0-8cb1-af66cdf8a709)

Could there be any problem with this code?

https://github.com/nomadkaraoke/python-audio-separator/blob/9eed6ca69d0ba468280931633ba5a34974f9b4cf/audio_separator/separator/separator.py#L315-L348

I tried to implement the same logic used in UVR, but it didn't work either.

https://github.com/Anjok07/ultimatevocalremovergui/blob/5517e0cf0d1acd16a1618eeedec596957523f9e1/UVR.py#L722-L746

I don't know much about Python, so I have some difficulty finding the problem.

**Comment by lannodev** [comment]
Thank you very much ❤️
